
package com.mycompany.bitacora.interfaz;

import java.awt.BorderLayout;

/**
 *
 * @author Jonathan Abarca
 */
public class Principal extends javax.swing.JFrame {

    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Principal = new javax.swing.JPanel();
        mnubPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniNuevoPunto = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bitácora de Mantenciónes");

        pnl_Principal.setOpaque(false);

        javax.swing.GroupLayout pnl_PrincipalLayout = new javax.swing.GroupLayout(pnl_Principal);
        pnl_Principal.setLayout(pnl_PrincipalLayout);
        pnl_PrincipalLayout.setHorizontalGroup(
            pnl_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 878, Short.MAX_VALUE)
        );
        pnl_PrincipalLayout.setVerticalGroup(
            pnl_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        jMenu1.setText("Nuevo Regis.");

        mniNuevoPunto.setText("Punto vaciado");
        mniNuevoPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNuevoPuntoActionPerformed(evt);
            }
        });
        jMenu1.add(mniNuevoPunto);

        jMenuItem1.setText("Tarea externa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        mnubPrincipal.add(jMenu1);

        jMenu2.setText("Ver Incidentes");
        mnubPrincipal.add(jMenu2);

        jMenu3.setText("Modificaciónes");
        mnubPrincipal.add(jMenu3);

        jMenu4.setText("Informes");
        mnubPrincipal.add(jMenu4);

        setJMenuBar(mnubPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniNuevoPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNuevoPuntoActionPerformed
        Pnl_NuevoPuntoVaciado miNuevoPunto = new Pnl_NuevoPuntoVaciado();
        miNuevoPunto.setSize(878, 496);
        miNuevoPunto.setLocation(0, 0);
        
        pnl_Principal.removeAll();
        pnl_Principal.add(miNuevoPunto,BorderLayout.CENTER);
        pnl_Principal.revalidate();
        pnl_Principal.repaint();
    }//GEN-LAST:event_mniNuevoPuntoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Pnl_TareaExtra miNuevaTarea = new Pnl_TareaExtra();
        miNuevaTarea.setSize(878, 496);
        miNuevaTarea.setLocation(0, 0);
        
        pnl_Principal.removeAll();
        pnl_Principal.add(miNuevaTarea,BorderLayout.CENTER);
        pnl_Principal.revalidate();
        pnl_Principal.repaint();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mniNuevoPunto;
    private javax.swing.JMenuBar mnubPrincipal;
    private javax.swing.JPanel pnl_Principal;
    // End of variables declaration//GEN-END:variables
}
